version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wallet_postgres
    restart: always
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wallet-app:
    build: .
    container_name: wallet_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/walletdb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
